import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight, Mic, ScanLine, Sparkles, Store, UsersRound, Volume2 } from "lucide-react";
import pottery from "@/assets/blue-pottery-vase.jpg";
import textiles from "@/assets/handwoven-textiles.jpg";
import baskets from "@/assets/jute-baskets.jpg";
import { Brand, Button } from "@/components/kala/ui";
import { languages } from "@/lib/kala-data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "KalaSetu AI — From Craft to Market" }, { name: "description", content: "Turn handmade products into professional catalogues and find the right buyers using AI." }, { property: "og:title", content: "KalaSetu AI — From Craft to Market" }, { property: "og:description", content: "AI-powered market linkage for marginalized Indian artisans." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Index,
});

function Index() {
  return <div className="min-h-screen overflow-hidden bg-background text-foreground"><header className="border-b border-border bg-background/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-10"><Brand /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#how-it-works" className="hover:text-foreground">How it works</a><a href="#ai-features" className="hover:text-foreground">AI features</a><a href="#impact" className="hover:text-foreground">Impact</a></nav><div className="flex items-center gap-2"><Link to="/buyer" className="hidden rounded-xl px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground sm:block">Find artisans</Link><Link to="/onboarding"><Button>Join as artisan <ArrowRight className="size-4" /></Button></Link></div></div></header>
    <main>
      <section className="craft-grid relative"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[.95fr_1.05fr] lg:items-center lg:px-10 lg:py-20"><div className="animate-rise-in"><p className="inline-flex items-center gap-2 rounded-full border border-terracotta/25 bg-terracotta-soft px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.16em] text-terracotta"><span className="size-1.5 rounded-full bg-terracotta animate-pulse-soft" /> Smart India Hackathon 2026 · SIH26090</p><h1 className="mt-6 max-w-3xl font-display text-[clamp(2.8rem,7vw,5.6rem)] font-bold leading-[.98] tracking-tight text-ink">Your Craft Deserves the <span className="text-terracotta">Right Market.</span></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">Turn your handmade products into professional digital catalogues and discover the right buyers using AI.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/onboarding"><Button className="min-h-12 px-5">Join as Artisan <ArrowRight className="size-4" /></Button></Link><Link to="/buyer"><Button variant="quiet" className="min-h-12 px-5">Find Artisans <UsersRound className="size-4" /></Button></Link></div><div className="mt-7 flex items-center gap-2 text-sm text-muted-foreground"><span className="grid size-8 place-items-center rounded-full bg-indigo text-primary-foreground"><Mic className="size-4" /></span><span>Voice-first in your language.</span><span className="font-medium text-terracotta">🎙️ Speak instead</span></div></div>
        <div className="relative animate-rise-in [animation-delay:120ms]"><div className="absolute -inset-5 rounded-[2rem] bg-saffron/20 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-border bg-card p-2 shadow-xl"><img src={pottery} alt="Hand-painted Jaipur blue pottery vase" width={912} height={912} className="aspect-[4/3] w-full rounded-[1.5rem] object-cover" /><div className="absolute left-6 top-6 rounded-xl border border-primary-foreground/20 bg-indigo/90 px-3 py-2 text-primary-foreground shadow-lg backdrop-blur"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-primary-foreground/70">AI catalogue ready</p><p className="mt-1 font-display text-lg font-bold">₹850 – ₹1,050</p></div><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-primary-foreground/20 bg-ink/90 p-4 text-primary-foreground backdrop-blur sm:left-auto sm:w-72"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.16em] text-primary-foreground/70">Best market match</p><p className="mt-1 font-display text-2xl font-bold">94%</p></div><div className="grid size-12 place-items-center rounded-full bg-saffron text-saffron-foreground"><Sparkles className="size-5" /></div></div><p className="mt-2 text-xs text-primary-foreground/75">Corporate Diwali gifting · ABC Enterprises</p></div></div></div>
      </div></section>
      <section id="how-it-works" className="border-b border-border bg-card"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-10"><div className="grid gap-4 md:grid-cols-4">{[{ n: "01", icon: ScanLine, title: "Take photo / speak", copy: "Show your craft or describe it in your own words." }, { n: "02", icon: Sparkles, title: "AI builds catalogue", copy: "Get a clear, professional product page to review." }, { n: "03", icon: Store, title: "Find market opportunities", copy: "See real briefs matched to your craft and capacity." }, { n: "04", icon: UsersRound, title: "Connect with buyers", copy: "Start the right conversation at the right time." }].map((step) => { const Icon = step.icon; return <div key={step.n} className="flex gap-3 rounded-xl p-3"><span className="font-mono text-xs text-terracotta">{step.n}</span><div><Icon className="size-5 text-indigo" /><p className="mt-2 font-display font-bold text-ink">{step.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{step.copy}</p></div></div>; })}</div></div></section>
      <section id="ai-features" className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-20"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-terracotta">Why KalaSetu is different</p><h2 className="mt-2 max-w-md font-display text-3xl font-bold tracking-tight text-ink sm:text-4xl">Not just digitized. <span className="text-indigo">Intelligently matched.</span></h2><p className="mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">One simple voice note can become a multilingual catalogue, a market signal, and a warm path to the right buyer.</p><div className="mt-6 space-y-3">{["Smart cataloguing from photo or voice", "Market opportunities ranked for fit", "Human review before anything is published", "Designed for low digital literacy"] .map((item) => <div key={item} className="flex items-center gap-3 text-sm font-medium"><span className="grid size-6 place-items-center rounded-full bg-moss-soft text-moss"><Check className="size-3.5" /></span>{item}</div>)}</div></div><div className="grid gap-4 sm:grid-cols-3"><div className="overflow-hidden rounded-2xl border border-border bg-card sm:col-span-2"><img src={textiles} alt="Handwoven Indian textiles" width={1200} height={900} loading="lazy" className="h-48 w-full object-cover sm:h-56" /><div className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-terracotta">For buyers</p><h3 className="mt-2 font-display text-xl font-bold">Find the story behind the supply.</h3><p className="mt-2 text-sm text-muted-foreground">Describe your requirement naturally. AI surfaces artisans who fit the brief.</p><Link to="/buyer" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-indigo">Build a requirement <ChevronRight className="size-4" /></Link></div></div><div className="overflow-hidden rounded-2xl border border-border bg-indigo text-primary-foreground sm:col-span-1"><img src={baskets} alt="Handmade jute baskets" width={1200} height={900} loading="lazy" className="h-36 w-full object-cover opacity-90" /><div className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary-foreground/65">For artisans</p><h3 className="mt-2 font-display text-xl font-bold">Your voice is enough to begin.</h3><p className="mt-2 text-sm text-primary-foreground/75">Simple tools. Clear choices. More ways to be seen.</p></div></div></div></section>
      <section id="impact" className="border-y border-border bg-surface-warm"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-center lg:px-10"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-terracotta">Built for every voice</p><h2 className="mt-2 font-display text-3xl font-bold text-ink">Speak your language, not a menu.</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">KalaSetu keeps the experience familiar for artisans across India, with more languages ready to be added as the network grows.</p><div className="mt-5 flex flex-wrap gap-2">{languages.map((language) => <span key={language} className="rounded-full border border-border bg-card px-3 py-1.5 text-sm font-medium">{language}</span>)}<span className="flex items-center gap-1 rounded-full border border-terracotta/30 bg-terracotta-soft px-3 py-1.5 text-sm font-medium text-terracotta"><Volume2 className="size-3.5" />Speak instead</span></div></div><div className="max-w-md rounded-2xl bg-terracotta p-6 text-primary-foreground shadow-lg"><p className="font-display text-xl font-bold leading-snug">“AI does not merely digitize an artisan’s product. It helps connect the right craft with the right market.”</p><div className="mt-6 flex flex-wrap gap-2"><Link to="/onboarding"><Button variant="secondary">Start as artisan <ArrowRight className="size-4" /></Button></Link><Link to="/buyer"><Button variant="quiet" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10">Find artisans</Button></Link></div></div></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-7 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-10"><p>KalaSetu AI · Smart India Hackathon 2026 · SIH26090</p><p>Prototype · Demo data only</p></footer>
  </div>;
}
