import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, ChevronRight, MapPin, Package, Sparkles, UsersRound } from "lucide-react";
import { opportunities, type Opportunity } from "@/lib/kala-data";
import { Button, MatchBar, Score, StatusBadge } from "@/components/kala/ui";

export function OpportunityCard({ opportunity, compact = false }: { opportunity: Opportunity; compact?: boolean }) {
  return <article className="rounded-2xl border border-border bg-card p-4 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md sm:p-5">
    <div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-terracotta">{opportunity.category}</p><h3 className="mt-1 font-display text-lg font-bold leading-tight text-ink">{opportunity.title}</h3><p className="mt-1 text-sm text-muted-foreground">{opportunity.buyer}</p></div><Score value={opportunity.score} /></div>
    <div className="mt-4"><MatchBar value={opportunity.score} /></div>
    <div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Quantity</p><p className="mt-0.5 font-medium">{opportunity.quantity}</p></div><div><p className="text-xs text-muted-foreground">Budget</p><p className="mt-0.5 font-medium">{opportunity.budget}</p></div><div><p className="text-xs text-muted-foreground">Location</p><p className="mt-0.5 font-medium">{opportunity.location}</p></div><div><p className="text-xs text-muted-foreground">Required by</p><p className="mt-0.5 font-medium">{opportunity.deadline.replace(" 2026", "")}</p></div></div>
    {!compact && <div className="mt-4 grid grid-cols-1 gap-1.5 text-xs text-muted-foreground sm:grid-cols-2">{opportunity.reasons.map((reason) => <span key={reason} className="flex items-center gap-1.5"><span className="text-moss">✓</span>{reason}</span>)}</div>}
    <div className="mt-5 flex gap-2"><Link to="/opportunities/$id" params={{ id: opportunity.id }} className="flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl border border-border px-3 py-2.5 text-sm font-semibold text-foreground transition-colors hover:bg-muted">View opportunity <ArrowRight className="size-4" /></Link>{!compact && <Button className="flex-1" onClick={() => window.alert("Interest noted in demo mode. The buyer will be notified when the connection API is connected.")}>Express interest</Button>}</div>
  </article>;
}

export function MiniOpportunity({ opportunity }: { opportunity: Opportunity }) { return <Link to="/opportunities/$id" params={{ id: opportunity.id }} className="group flex items-center gap-3 rounded-xl border border-border bg-card p-3 transition-colors hover:bg-muted"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-saffron/20 text-terracotta"><Sparkles className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink">{opportunity.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{opportunity.buyer} · {opportunity.quantity}</p></div><div className="text-right"><p className="font-display font-bold text-indigo">{opportunity.score}%</p><p className="font-mono text-[9px] uppercase tracking-[.1em] text-muted-foreground">match</p></div><ChevronRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></Link>; }

export function OpportunityMeta({ opportunity }: { opportunity: Opportunity }) { return <div className="grid gap-3 sm:grid-cols-2"><div className="flex gap-3 rounded-xl bg-muted/60 p-3"><UsersRound className="mt-0.5 size-4 text-terracotta" /><div><p className="text-xs text-muted-foreground">Buyer</p><p className="mt-0.5 text-sm font-semibold">{opportunity.buyer}</p></div></div><div className="flex gap-3 rounded-xl bg-muted/60 p-3"><Package className="mt-0.5 size-4 text-terracotta" /><div><p className="text-xs text-muted-foreground">Requirement</p><p className="mt-0.5 text-sm font-semibold">{opportunity.quantity}</p></div></div><div className="flex gap-3 rounded-xl bg-muted/60 p-3"><MapPin className="mt-0.5 size-4 text-terracotta" /><div><p className="text-xs text-muted-foreground">Location</p><p className="mt-0.5 text-sm font-semibold">{opportunity.location}</p></div></div><div className="flex gap-3 rounded-xl bg-muted/60 p-3"><CalendarDays className="mt-0.5 size-4 text-terracotta" /><div><p className="text-xs text-muted-foreground">Deadline</p><p className="mt-0.5 text-sm font-semibold">{opportunity.deadline}</p></div></div></div>; }

export function OpportunityList({ limit }: { limit?: number }) { return <div className="grid gap-4 xl:grid-cols-2">{(limit ? opportunities.slice(0, limit) : opportunities).map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div>; }

export function EnquiryStatus({ status }: { status: string }) { return <StatusBadge status={status} />; }